[package]
edition = "2021"
name = "ai-client"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4.38", features = ["serde"]}
common = {path = "../common"}
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
tokio = "1.38.0"
tokio-tungstenite = "0.23.0"
