
[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile]

[profile.dioxus-wasm]
inherits = "dev"
opt-level = 2

[profile.dioxus-server]
inherits = "dev"
opt-level = 2

[profile.dioxus-android]
inherits = "dev"
opt-level = 2
