[package]
edition = "2021"
name = "ai"
version = "0.1.0"

[dependencies]
common = {path = "../common"}
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", default-features = false, features = ["fmt", "ansi", "env-filter", "tracing-log"]}
# [lib]
# name = "ai"
# path = "src/lib.rs"
