[package]
edition = "2021"
name = "common"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4.38", features = ["serde"]}
fastrand = "2.0.2"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
tracing = "0.1.40"
