export const EXAMPLE = {
  bids: {},
  curr_played_cards: [
    { id: 18, played_by: null, suit: "club", value: 6 },
    { id: 15, played_by: null, suit: "spade", value: 5 },
    { id: 43, played_by: null, suit: "spade", value: 12 },
    { id: 2, played_by: null, suit: "club", value: 2 },
  ],
  curr_player_turn: "a",
  curr_round: 2,
  curr_winning_card: null,
  dealing_order: ["a", "q"],
  deck: [
    { id: 47, played_by: null, suit: "spade", value: 13 },
    { id: 7, played_by: null, suit: "spade", value: 3 },
    { id: 19, played_by: null, suit: "spade", value: 6 },
    { id: 40, played_by: null, suit: "heart", value: 12 },
    { id: 16, played_by: null, suit: "heart", value: 6 },
    { id: 1, played_by: null, suit: "diamond", value: 2 },
    { id: 3, played_by: null, suit: "spade", value: 2 },
    { id: 50, played_by: null, suit: "club", value: 14 },
    { id: 22, played_by: null, suit: "club", value: 7 },
    { id: 13, played_by: null, suit: "diamond", value: 5 },
    { id: 21, played_by: null, suit: "diamond", value: 7 },
    { id: 28, played_by: null, suit: "heart", value: 9 },
    { id: 34, played_by: null, suit: "club", value: 10 },
    { id: 44, played_by: null, suit: "heart", value: 13 },
    { id: 26, played_by: null, suit: "club", value: 8 },
    { id: 37, played_by: null, suit: "diamond", value: 11 },
    { id: 33, played_by: null, suit: "diamond", value: 10 },
    { id: 5, played_by: null, suit: "diamond", value: 3 },
    { id: 23, played_by: null, suit: "spade", value: 7 },
    { id: 29, played_by: null, suit: "diamond", value: 9 },
    { id: 46, played_by: null, suit: "club", value: 13 },
    { id: 20, played_by: null, suit: "heart", value: 7 },
    { id: 51, played_by: null, suit: "spade", value: 14 },
    { id: 25, played_by: null, suit: "diamond", value: 8 },
    { id: 8, played_by: null, suit: "heart", value: 4 },
    { id: 39, played_by: null, suit: "spade", value: 11 },
    { id: 27, played_by: null, suit: "spade", value: 8 },
    { id: 17, played_by: null, suit: "diamond", value: 6 },
    { id: 35, played_by: null, suit: "spade", value: 10 },
    { id: 9, played_by: null, suit: "diamond", value: 4 },
    { id: 42, played_by: null, suit: "club", value: 12 },
    { id: 36, played_by: null, suit: "heart", value: 11 },
    { id: 4, played_by: null, suit: "heart", value: 3 },
    { id: 41, played_by: null, suit: "diamond", value: 12 },
    { id: 18, played_by: null, suit: "club", value: 6 },
    { id: 15, played_by: null, suit: "spade", value: 5 },
    { id: 43, played_by: null, suit: "spade", value: 12 },
    { id: 2, played_by: null, suit: "club", value: 2 },
    { id: 14, played_by: null, suit: "club", value: 5 },
    { id: 32, played_by: null, suit: "heart", value: 10 },
    { id: 0, played_by: null, suit: "heart", value: 2 },
    { id: 10, played_by: null, suit: "club", value: 4 },
    { id: 48, played_by: null, suit: "heart", value: 14 },
    { id: 6, played_by: null, suit: "club", value: 3 },
    { id: 31, played_by: null, suit: "spade", value: 9 },
    { id: 38, played_by: null, suit: "club", value: 11 },
    { id: 49, played_by: null, suit: "diamond", value: 14 },
    { id: 11, played_by: null, suit: "spade", value: 4 },
    { id: 24, played_by: null, suit: "heart", value: 8 },
    { id: 45, played_by: null, suit: "diamond", value: 13 },
  ],
  event_log: [],
  play_order: ["q", "a"],
  players: {
    a: {
      hand: [
        { id: 12, played_by: "a", suit: "heart", value: 5 },
        { id: 45, played_by: null, suit: "diamond", value: 13 },
      ],
      id: "a",
      order: 0,
      role: "Player",
      round: 0,
      state: "Idle",
      trump: "heart",
    },
    q: {
      hand: [
        { id: 30, played_by: "q", suit: "club", value: 9 },
        { id: 45, played_by: null, suit: "diamond", value: 1 },
      ],
      id: "q",
      order: 0,
      role: "Player",
      round: 0,
      state: "Idle",
      trump: "heart",
    },
  },
  score: { a: 0, q: 0 },
  state: "Bid",
  system_status: [],
  trump: "heart",
  wins: { a: 0, q: 0 },
};

export const LOBBYCODE_KEY = "lobbyCodeKey";
export const USERNAME_KEY = "usernameKey";
export const SECRET_KEY = "secretKey";
