# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
    # branches: [ ]
  pull_request:
    branches: [main]
    # branches: [ ]

jobs:
  ci:
    name: +ci
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      DOCKERHUB_USERNAME: "${{secrets.DOCKERHUB_USERNAME}}"
      DOCKERHUB_TOKEN: "${{secrets.DOCKERHUB_TOKEN}}"
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions/setup-earthly@v1
      - name: Run +all on Earthly satellite
        if: github.ref == 'refs/heads/main'
        run: earthly --org jeremyarde --ci --satellite my-satellite +all
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Docker Login
        # run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
        run: echo $DOCKERHUB_TOKEN | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - name: Earthly version
        run: earthly --version
      - name: Run build and push
        env:
          ENVIRONMENT: production
        run: earthly --push +docker

  cd:
    name: +cd
    runs-on: ubuntu-latest
    needs: ci
    env:
      FORCE_COLOR: 1
    steps:
      - name: Send request to trigger deploy
        run: curl https://api.render.com/deploy/srv-cq0od33v2p9s73cdroe0?key=ycr2DX977tM
